version: '3'

networks:
  zack-raft:
    driver: bridge

volumes:
  node-1-logs: {}
  node-2-logs: {}
  node-3-logs: {}

services:
  zack-gateway-api:
    container_name: zack-gateway-api
    build:
      context: ..
      dockerfile: ./Gateway-API/Dockerfile
    environment:
      NODE_ONE: "zack-node-api-1:8080"
      NODE_TWO: "zack-node-api-2:8080"
      NODE_THREE: "zack-node-api-3:8080"
    ports:
      - 1400:8080
    networks:
      - zack-raft

  zack-node-api-1:
    container_name: zack-node-api-1
    user: 0:0
    entrypoint:
      - /bin/bash
      - -c 
      - |
        mkdir -p /app/RaftLogs
        chown -R app:app /app/RaftLogs
        chmod -R 755 /app/RaftLogs
        su app -c "dotnet Node-API.dll"
    build:
      context: ..
      dockerfile: ./Node-API/Dockerfile
    environment:
      NODE_ONE: "zack-node-api-1:8080"
      NODE_TWO: "zack-node-api-2:8080"
      NODE_THREE: "zack-node-api-3:8080"
    ports:
      - 1401:8080
    volumes:
    - node-1-logs:/app/RaftLogs
    networks:
      - zack-raft

  zack-node-api-2:
    container_name: zack-node-api-2
    user: 0:0
    entrypoint:
      - /bin/bash
      - -c 
      - |
        mkdir -p /app/RaftLogs
        chown -R app:app /app/RaftLogs
        chmod -R 755 /app/RaftLogs
        su app -c "dotnet Node-API.dll"
    build:
      context: ..
      dockerfile: ./Node-API/Dockerfile
    environment:
      NODE_ONE: "zack-node-api-2:8080"
      NODE_TWO: "zack-node-api-1:8080"
      NODE_THREE: "zack-node-api-3:8080"
    ports:
      - 1402:8080
    volumes:
    - node-2-logs:/app/RaftLogs
    networks:
      - zack-raft

  zack-node-api-3:
    container_name: zack-node-api-3
    user: 0:0
    entrypoint:
      - /bin/bash
      - -c 
      - |
        mkdir -p /app/RaftLogs
        chown -R app:app /app/RaftLogs
        chmod -R 755 /app/RaftLogs
        su app -c "dotnet Node-API.dll"
    environment:
      NODE_ONE: "zack-node-api-3:8080"
      NODE_TWO: "zack-node-api-2:8080"
      NODE_THREE: "zack-node-api-1:8080"
    build:
      context: ..
      dockerfile: ./Node-API/Dockerfile
    ports:
      - 1403:8080
    volumes:
    - node-3-logs:/app/RaftLogs
    networks:
      - zack-raft

  zack-raft-web:
    container_name: "zack-web"
    build:
      context: ..
      dockerfile: ./Raft-Web/Dockerfile
      args:
        GATEWAY_URL_ARG: "http://localhost:1400"
    ports:
      - 1404:80
    networks:
      - zack-raft
