name: Zack Raft Actions
run-name: ${{github.actor}} is pushing a new version of raft
on: [push, workflow_dispatch]

env:
  DOTNET_CORE_VERSION: 8.0.x
  CONFIGURATION: Release
  GATEWAY_API_WORKING_DIRECTORY: Gateway-API
  NODE_API_WORKING_DIRECTORY: Node-API

jobs:
  Test-Then-Deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Set up Tests
        run: |
          cd Testing
          docker compose up -d --build
          sleep 10
          docker compose exec zack-test dotnet test
          sleep 5
          docker compose exec --exit-code-from zack-test

      - name: Clean up Tests
        if: always()
        run: |
          cd Testing
          docker compose down --remove-orphans --volumes

      - name: Set Up Production
        run: |
          cd Production
          docker compose down --remove-orphans
          docker compose up -d --build

      # - name: Ensure Formatting
      #   run: dotnet format --verify-no-changes --verbosity diagnostic